name: Build Multi-Cloud Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Add permissions for OIDC token
permissions:
  id-token: write
  contents: read

jobs:

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "1.8.5"
      - name: Initialize Packer
        run: packer init .
      - name: Format Packer Files
        run: packer fmt .

  validate:
    needs: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "1.8.5"
      - name: Initialize Packer
        run: packer init .
      - name: Validate Packer Files
        run: packer validate .

  build-aws:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "1.8.5"
      
      - name: Initialize Packer
        run: packer init packer/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::291847254387:role/GitHubPipeline
          aws-region: us-east-2
          role-session-name: GitHubPipeline

      # Create Packer Variables File
      - name: Create Packer Variables File
        run: |
          cat << EOF > packer/build.pkrvars.hcl
          secagent_url = "${{ secrets.INFORMATICA_AGENT_URL }}"
          aws_region = "us-east-2"
          instance_type = "t3.medium"
          EOF

      - name: Build AWS Image
        env:
          PACKER_LOG: 1
        run: packer build -var-file="packer/build.pkrvars.hcl" -only="informatica-aws.*" packer/

  aws-addons:
    needs: build-aws
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "1.8.5"

      - name: Initialize Packer
        run: packer init .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::291847254387:role/GitHubPipeline
          aws-region: us-east-2
          role-session-name: GitHubPipeline

      - name: Create Packer Variables File
        run: |
          cat << EOF > build.pkrvars.hcl
          base_ami_id = "${{ needs.build-aws.outputs.ami_id }}"
          aws_region  = "us-east-2"
          EOF

      - name: Add AWS Tools to Base Image
        run: |
          packer build -var-file="build.pkrvars.hcl" -only="aws-addons.*" .