name: Build Multi-Cloud Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Add permissions for OIDC token
permissions:
  id-token: write
  contents: read

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "1.8.5"
      
      - name: Initialize Packer
        run: packer init packer/
      
      - name: Format Packer Files
        run: packer fmt packer/

  validate:
    needs: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "1.8.5"
      
      - name: Initialize Packer
        run: packer init packer/
      
      - name: Validate Packer Files
        run: packer validate packer/

  build-aws:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "1.8.5"
      
      - name: Initialize Packer
        run: packer init packer/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::291847254387:role/GitHubPipeline
          aws-region: us-east-2
          role-session-name: GitHubPipeline

      # Create Packer Variables File
      - name: Create Packer Variables File
        run: |
          cat << EOF > packer/variables.auto.pkrvars.hcl
          aws_region = "us-east-2"
          instance_type = "t3.medium"
          EOF

      - name: Build AWS Image
        env:
          PACKER_LOG: 1
        run: |
          packer build -only="aws-base.*" packer/

  build-azure:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "1.8.5"
      
      - name: Initialize Packer
        run: packer init packer/

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Configure Azure Credentials
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
          environment: 'AzureCloud'
          auth-type: 'IDENTITY'

      - name: Configure Azure Credentials for Packer
        uses: azure/login@v2
        with:
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          auth-type: 'SERVICE_PRINCIPAL'

      - name: Build Azure Image
        run: packer build -only="azure-base.*" packer/
        
